### ISSUE TITLE
Are these really FE questions?

### ISSUE THREAD

**Issue by flyingace** [lei-clearsky/learning-notes#1]
I value improving ourselves with increased CS knowledge, but one of the things I find most frustrating in an interview for a FE position is being asked questions which are very far from issues I might actually face in practice. How many of the questions in this repo deal with issues we might actually face in practice or are even really FE questions?

Example: https://github.com/lei-clearsky/front-end-interview-questions/tree/master/arrayToTree

**Comment by lei-clearsky** [comment]
Actually I was planning to have a few sections in this repo, such as html questions, css questions, javascript question, general question, algorithm question, etc. Haven't got a chance to update those yet. Also thinking adding an interface can be more readable and easier to navigate? such as https://www.gitbook.com/
